-- AlterTable
ALTER TABLE "CoreSet" ADD COLUMN     "isBodyWeight" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "reps" SET DEFAULT 0,
ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "weight" SET DEFAULT 0,
ALTER COLUMN "restTime" SET DEFAULT 60;
